//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.MNS_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MNS_Service.IWeb_Service_MNS")]
    public interface IWeb_Service_MNS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb_Service_MNS/OnCalc", ReplyAction="http://tempuri.org/IWeb_Service_MNS/OnCalcResponse")]
        float[] OnCalc(
                    int[] In_r, 
                    float[] z_r, 
                    int nr, 
                    int[] In_c, 
                    float[] z_c, 
                    int nc, 
                    int[] In_l, 
                    float[] z_l, 
                    int nl, 
                    int nv, 
                    int lp, 
                    int lm, 
                    int kp, 
                    int km, 
                    float[] f, 
                    int nf, 
                    int nju, 
                    int[] In_ju, 
                    float[] Z_ju, 
                    int neu, 
                    int[] In_eu, 
                    float[] Z_eu, 
                    int nji, 
                    int[] In_ji, 
                    float[] Z_ji, 
                    int nou, 
                    int[] In_ou, 
                    float[] Z_ou, 
                    int ntri, 
                    int[] In_tri, 
                    float[] z_tri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb_Service_MNS/OnCalc", ReplyAction="http://tempuri.org/IWeb_Service_MNS/OnCalcResponse")]
        System.Threading.Tasks.Task<float[]> OnCalcAsync(
                    int[] In_r, 
                    float[] z_r, 
                    int nr, 
                    int[] In_c, 
                    float[] z_c, 
                    int nc, 
                    int[] In_l, 
                    float[] z_l, 
                    int nl, 
                    int nv, 
                    int lp, 
                    int lm, 
                    int kp, 
                    int km, 
                    float[] f, 
                    int nf, 
                    int nju, 
                    int[] In_ju, 
                    float[] Z_ju, 
                    int neu, 
                    int[] In_eu, 
                    float[] Z_eu, 
                    int nji, 
                    int[] In_ji, 
                    float[] Z_ji, 
                    int nou, 
                    int[] In_ou, 
                    float[] Z_ou, 
                    int ntri, 
                    int[] In_tri, 
                    float[] z_tri);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeb_Service_MNSChannel : WebClient.MNS_Service.IWeb_Service_MNS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Web_Service_MNSClient : System.ServiceModel.ClientBase<WebClient.MNS_Service.IWeb_Service_MNS>, WebClient.MNS_Service.IWeb_Service_MNS {
        
        public Web_Service_MNSClient() {
        }
        
        public Web_Service_MNSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Web_Service_MNSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Web_Service_MNSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Web_Service_MNSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float[] OnCalc(
                    int[] In_r, 
                    float[] z_r, 
                    int nr, 
                    int[] In_c, 
                    float[] z_c, 
                    int nc, 
                    int[] In_l, 
                    float[] z_l, 
                    int nl, 
                    int nv, 
                    int lp, 
                    int lm, 
                    int kp, 
                    int km, 
                    float[] f, 
                    int nf, 
                    int nju, 
                    int[] In_ju, 
                    float[] Z_ju, 
                    int neu, 
                    int[] In_eu, 
                    float[] Z_eu, 
                    int nji, 
                    int[] In_ji, 
                    float[] Z_ji, 
                    int nou, 
                    int[] In_ou, 
                    float[] Z_ou, 
                    int ntri, 
                    int[] In_tri, 
                    float[] z_tri) {
            return base.Channel.OnCalc(In_r, z_r, nr, In_c, z_c, nc, In_l, z_l, nl, nv, lp, lm, kp, km, f, nf, nju, In_ju, Z_ju, neu, In_eu, Z_eu, nji, In_ji, Z_ji, nou, In_ou, Z_ou, ntri, In_tri, z_tri);
        }
        
        public System.Threading.Tasks.Task<float[]> OnCalcAsync(
                    int[] In_r, 
                    float[] z_r, 
                    int nr, 
                    int[] In_c, 
                    float[] z_c, 
                    int nc, 
                    int[] In_l, 
                    float[] z_l, 
                    int nl, 
                    int nv, 
                    int lp, 
                    int lm, 
                    int kp, 
                    int km, 
                    float[] f, 
                    int nf, 
                    int nju, 
                    int[] In_ju, 
                    float[] Z_ju, 
                    int neu, 
                    int[] In_eu, 
                    float[] Z_eu, 
                    int nji, 
                    int[] In_ji, 
                    float[] Z_ji, 
                    int nou, 
                    int[] In_ou, 
                    float[] Z_ou, 
                    int ntri, 
                    int[] In_tri, 
                    float[] z_tri) {
            return base.Channel.OnCalcAsync(In_r, z_r, nr, In_c, z_c, nc, In_l, z_l, nl, nv, lp, lm, kp, km, f, nf, nju, In_ju, Z_ju, neu, In_eu, Z_eu, nji, In_ji, Z_ji, nou, In_ou, Z_ou, ntri, In_tri, z_tri);
        }
    }
}
